# Generated by Django 6.0 on 2025-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='poc_user',
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(max_length=100),
        ),
    ]
