# Generated by Django 6.0 on 2025-12-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clientprofile_memberprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('ELITE', 'Elite'), ('CORE', 'Core'), ('DIGITAL', 'Digital')], max_length=20),
        ),
    ]
