# Generated by Django 6.0 on 2025-12-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clientprofile_created_at_clientprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('Elite', 'ELITE'), ('Core', 'CORE'), ('Digital', 'DIGITAL')], max_length=20),
        ),
    ]
