# Generated by Django 6.0 on 2025-12-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='size_of_business',
            new_name='size',
        ),
    ]
