# Generated by Django 6.0 on 2025-12-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_created_at_company_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
