# Generated by Django 6.0 on 2025-12-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companypoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companypoc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_pocs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypoc',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_pocs_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
